### ISSUE TITLE
Option to ignore <BR> elements

### ISSUE THREAD

**Issue by simongray** [kuhumcst/clarin-tei#1]
# Problem statement
Many of the TEI documents on Clarin.dk are extemely narrow, making reading them pretty hard if once is to respect the original formatting. An option to enable/disable this on-demand could be pretty useful.

# Implementation
This could be implemented as 

```css
br { display: none; }
```

However, one complication is the fact that it would need to also apply to shadow-dom elements since it is used in the TEI reader. Perhaps the way to do it is by setting a variable in the page :root and using this as the display value for <br> in tei.css, e.g.

```css
br { display: var(--tei-br-display) ; }
```

Unsure if this would work. Another option is to rebuild the Hiccup every time this setting changes.
